
{
    'name': 'Saudi HR Customize',
    'summary': 'Saudi HR Customize',
    'author': "MarketMe , Mahmoud Elfeky",
    'company': 'MarketMe',
    'website': "https://www.linkedin.com/company/marketme-hh/",
    'version': '12.0.0.1.0',
    'category': 'HR',
    'license': 'AGPL-3',
    'sequence': 1,
    'depends': [
        'base',
        'mail',
        'hr',
        'hr_contract',
        'hr_payroll',
        'hr_holidays',
        'account',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'report/',
        # 'wizard/',
        'views/hr_contract.xml',
        # 'views/hr_award.xml',
        'views/hr_permission.xml',
        'views/hr_resignation.xml',
        'views/hr_transfer.xml',
        'views/hr_ticket.xml',
        'views/travel_allowances.xml',
        'views/hr_overtime.xml',
        'views/hr_salary_scale.xml',
        'views/res_config_settings.xml',
        'views/menu.xml',
        'data/data.xml',
        # 'data/ir_cron.xml',
        'data/salary_rules.xml',
    ],
    'demo': [
        # 'demo/',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}

